# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Frmt < Formula
  desc ""
  homepage "https://github.com/Shobhit-Nagpal/frmt"
  version "0.2"

  on_macos do
    url "https://github.com/Shobhit-Nagpal/frmt/releases/download/v0.2/frmt_0.2_darwin_all.tar.gz"
    sha256 "00c66cb19b5d7938008ffc5539c23fbfddbd539ec7ea66708fbe5bd4c04d7209"

    def install
      bin.install "frmt"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Shobhit-Nagpal/frmt/releases/download/v0.2/frmt_0.2_linux_arm64.tar.gz"
      sha256 "412ce0060201822fcdedf42405d01c789d1d97202e31282b9365849d929c1f78"

      def install
        bin.install "frmt"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Shobhit-Nagpal/frmt/releases/download/v0.2/frmt_0.2_linux_amd64.tar.gz"
      sha256 "34c2c44eaf3ae2e178552399834e8ac451e16cbe4a829c66c73a4f2394e23ff3"

      def install
        bin.install "frmt"
      end
    end
  end
end
