# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Frmt < Formula
  desc ""
  homepage "https://github.com/Shobhit-Nagpal/frmt"
  version "0.1"

  on_macos do
    url "https://github.com/Shobhit-Nagpal/frmt/releases/download/v0.1/frmt_0.1_darwin_all.tar.gz"
    sha256 "ea5ed5134f85f4fef8e4d91e80349ed6b6a215b4da11046ab5c3ad1ebb5c3272"

    def install
      bin.install "frmt"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Shobhit-Nagpal/frmt/releases/download/v0.1/frmt_0.1_linux_arm64.tar.gz"
      sha256 "2241688e4132c56ebda4ddea89b44fc07d33a749e76edd8f9e56d52de300f77a"

      def install
        bin.install "frmt"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Shobhit-Nagpal/frmt/releases/download/v0.1/frmt_0.1_linux_amd64.tar.gz"
      sha256 "36cb834838e0b8f0d40b74365f1a85c67c4ca3bd308a7691c54345bfc4030089"

      def install
        bin.install "frmt"
      end
    end
  end
end
