# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Frmt < Formula
  desc ""
  homepage "https://github.com/Shobhit-Nagpal/frmt"
  version "0.7"

  on_macos do
    url "https://github.com/Shobhit-Nagpal/frmt/releases/download/v0.7/frmt_0.7_darwin_all.tar.gz"
    sha256 "6ef48d2bfc5df3ec065e52aa2e59aada4550f87edfbe3e5e599921701aa6dff9"

    def install
      bin.install "frmt"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Shobhit-Nagpal/frmt/releases/download/v0.7/frmt_0.7_linux_arm64.tar.gz"
      sha256 "b8a43733f2950e1b567e617a889549d8bfcd48d4262ce056b8b6f6d9251f5a28"

      def install
        bin.install "frmt"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Shobhit-Nagpal/frmt/releases/download/v0.7/frmt_0.7_linux_amd64.tar.gz"
      sha256 "46ea3963a277a8ffc6884b9aff1deae9070ca3f5c4f2ac4c77973be56dbbc7d0"

      def install
        bin.install "frmt"
      end
    end
  end
end
