# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Frmt < Formula
  desc "Convert file formats from the CLI"
  homepage "https://github.com/Shobhit-Nagpal/frmt"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Shobhit-Nagpal/frmt/releases/download/v1.0.0/frmt_Darwin_x86_64.tar.gz"
      sha256 "73cde80795b263535231a27730a3d06b3e2bca83d2f4f02078e35b5ecf355a78"

      def install
        bin.install "frmt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Shobhit-Nagpal/frmt/releases/download/v1.0.0/frmt_Darwin_arm64.tar.gz"
      sha256 "65ba288ffb3928425532799732b6d4188d1c49872e689e8a96be376c85290bc3"

      def install
        bin.install "frmt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Shobhit-Nagpal/frmt/releases/download/v1.0.0/frmt_Linux_x86_64.tar.gz"
      sha256 "7ca806fb161f5f15b09bfcf7f74f5c2d65925a6372d8cf3bef053b07de4c4592"

      def install
        bin.install "frmt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Shobhit-Nagpal/frmt/releases/download/v1.0.0/frmt_Linux_arm64.tar.gz"
      sha256 "a7fa6d2679e0eb3d8c582a0101036f0a191647c10e84564aa3c32c4048b6aba0"

      def install
        bin.install "frmt"
      end
    end
  end
end
